# Generated by Django 3.0.11 on 2021-08-21 12:30

from django.db import migrations, models
import django.db.models.deletion
import helpdesk.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('username', models.CharField(default=None, max_length=255, verbose_name='username')),
                ('ticket', models.CharField(default=None, max_length=5, verbose_name='ticket')),
                ('problem', models.TextField(blank=True, default=None, null=True)),
                ('des_problem', models.TextField(blank=True, default=None, null=True)),
                ('obs_tecnico', models.TextField(blank=True, default=None, null=True)),
                ('name', models.CharField(default=None, max_length=255, verbose_name='name')),
                ('data', models.CharField(default=None, max_length=50, verbose_name='data')),
                ('finalizado', models.CharField(default=None, max_length=100, verbose_name='finalizado')),
                ('grupo', models.CharField(default=None, max_length=20, verbose_name='grupo')),
                ('file', models.FileField(blank=True, null=True, upload_to=helpdesk.models.get_files_path, verbose_name='arquivos')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], default=None, max_length=10, verbose_name='urgencia')),
                ('status', models.CharField(choices=[('em atendimento', 'em atendimento'), ('aberto', 'aberto'), ('resolvido', 'resolvido'), ('aguardando', 'aguardando')], default='aberto', max_length=100, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-ticket'],
            },
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('img', models.ImageField(blank=True, null=True, upload_to=helpdesk.models.get_files_path)),
                ('link', models.CharField(max_length=255, verbose_name='link')),
            ],
            options={
                'verbose_name': 'ImageLink',
                'verbose_name_plural': 'ImageLinks',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('From', models.CharField(default=None, max_length=100, verbose_name='from')),
                ('mensagem', models.CharField(default=None, max_length=500, verbose_name='mensagem')),
                ('nome', models.CharField(default=None, max_length=100, verbose_name='nome')),
                ('idChat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Chamado')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
    ]
