# Generated by Django 3.0.11 on 2021-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aguardando', 'aguardando'), ('aberto', 'aberto'), ('resolvido', 'resolvido'), ('em atendimento', 'em atendimento')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Alta', 'Alta'), ('Media', 'Media')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
