# Generated by Django 3.0.11 on 2021-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_chamado_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baixa', 'Baixa'), ('Media', 'Media')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
