# Generated by Django 3.0.11 on 2021-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20210408_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('fechado', 'fechado'), ('aguardando', 'aguardando'), ('em atendimento', 'em atendimento'), ('aberto', 'aberto')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
