# Generated by Django 3.0.11 on 2021-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20210701_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('fechado', 'fechado'), ('em atendimento', 'em atendimento'), ('aguardando', 'aguardando'), ('aberto', 'aberto')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Alta', 'Alta'), ('Media', 'Media')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
