# Generated by Django 3.0.11 on 2021-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_auto_20210821_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data',
            field=models.DateTimeField(default=None, max_length=50, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aguardando', 'aguardando'), ('em atendimento', 'em atendimento'), ('resolvido', 'resolvido'), ('aberto', 'aberto')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Media', 'Media'), ('Baixa', 'Baixa'), ('Alta', 'Alta')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
