# Generated by Django 3.0.11 on 2021-07-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_auto_20210714_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'aberto'), ('aguardando', 'aguardando'), ('resolvido', 'resolvido'), ('em atendimento', 'em atendimento')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Media', 'Media'), ('Baixa', 'Baixa'), ('Alta', 'Alta')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
