# Generated by Django 3.0.11 on 2021-09-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_auto_20210827_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('em atendimento', 'em atendimento'), ('resolvido', 'resolvido'), ('aberto', 'aberto'), ('aguardando', 'aguardando')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
