# Generated by Django 3.1.2 on 2021-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_auto_20210416_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('fechado', 'fechado'), ('em atendimento', 'em atendimento'), ('aguardando', 'aguardando'), ('aberto', 'aberto')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baixa', 'Baixa'), ('Media', 'Media')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
