# Generated by Django 3.0.11 on 2021-09-10 18:23

from django.db import migrations, models
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_auto_20210903_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=helpdesk.models.get_file_path, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('em atendimento', 'em atendimento'), ('aguardando', 'aguardando'), ('aberto', 'aberto'), ('resolvido', 'resolvido')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Media', 'Media'), ('Alta', 'Alta'), ('Baixa', 'Baixa')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
