# Generated by Django 3.2.4 on 2021-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_auto_20210628_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('fechado', 'fechado'), ('aberto', 'aberto'), ('aguardando', 'aguardando'), ('em atendimento', 'em atendimento')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
