# Generated by Django 3.2.4 on 2021-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_auto_20210628_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('em atendimento', 'em atendimento'), ('aguardando', 'aguardando'), ('fechado', 'fechado'), ('aberto', 'aberto')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baixa', 'Baixa'), ('Media', 'Media')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
