# Generated by Django 3.2.4 on 2021-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_auto_20210628_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aguardando', 'aguardando'), ('aberto', 'aberto'), ('em atendimento', 'em atendimento'), ('fechado', 'fechado')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Alta', 'Alta'), ('Media', 'Media')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
