# Generated by Django 3.2.4 on 2021-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_auto_20210628_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('em atendimento', 'em atendimento'), ('fechado', 'fechado'), ('aguardando', 'aguardando'), ('aberto', 'aberto')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], default=None, max_length=10, verbose_name='urgencia'),
        ),
    ]
