# Generated by Django 3.0.11 on 2021-08-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0028_auto_20210730_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aguardando', 'aguardando'), ('resolvido', 'resolvido'), ('aberto', 'aberto'), ('em atendimento', 'em atendimento')], default='aberto', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='urgency',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa')], default=None, max_length=10, verbose_name='urgencia'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='mensagem',
            field=models.CharField(default=None, max_length=500, verbose_name='mensagem'),
        ),
    ]
