# Generated by Django 3.0.11 on 2021-06-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Outro', 'Outro'), ('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
