# Generated by Django 3.0.11 on 2021-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopessoal',
            name='cod_mec',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='codigo mecauto'),
        ),
    ]
