# Generated by Django 3.0.11 on 2021-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], default=None, max_length=20, verbose_name='Genero'),
        ),
    ]
