# Generated by Django 3.0.11 on 2021-04-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210406_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodocumentos',
            name='documento',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usuariodocumentos',
            name='numerodocumento',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='NumeroDocumento'),
        ),
        migrations.AlterField(
            model_name='usuariodocumentos',
            name='orgao',
            field=models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='orgao'),
        ),
        migrations.AlterField(
            model_name='usuarioendereco',
            name='cep',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='usuarioendereco',
            name='logradouro',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='usuarioendereco',
            name='numero',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='usuarioendereco',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=2, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuarioendereco',
            name='ufatual',
            field=models.CharField(blank=True, default=None, max_length=2, null=True, verbose_name='UfAtual'),
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Outro', 'Outro'), ('Feminino', 'Feminino')], default=None, max_length=20, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='cargahorariam',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='CargaHorariaM'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='categoria',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='codigofuncao',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='CodigoFuncao'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='departamento',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='empresa',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='indicativoadmissao',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='IndicativoAdmissao'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='naturezaatividade',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='NaturezaAtividade'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='primeiroemprego',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='PrimeiroEmprego'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='regimejornada',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='RegimeJornada'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='regimeprevidenciario',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='RegimePrevidenciario'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='regimetrabalho',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='RegimeTrabalho'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='salariovariavel',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='tipoAdmissao',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='tipoAdmissao'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='unidadesalarial',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='UnidadeSalarial'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='valetransporte',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='valetransporte'),
        ),
    ]
