# Generated by Django 3.0.11 on 2021-04-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210406_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='codigo',
            field=models.IntegerField(default='0', null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Outro', 'Outro'), ('Masculino', 'Masculino')], default='#', max_length=20, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='ufcarteiratrabalho',
            field=models.CharField(default='#', max_length=2, verbose_name='UfCarteiraTrabalho'),
        ),
    ]
