# Generated by Django 3.0.11 on 2021-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuariopessoal_cod_mec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='nome do grupo')),
            ],
            options={
                'verbose_name': 'grupo de permissões',
                'verbose_name_plural': 'grupos de permissões',
            },
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='gender',
            field=models.CharField(blank=True, choices=[('Outro', 'Outro'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
