# Generated by Django 3.0.11 on 2021-07-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210701_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Outro', 'Outro'), ('Masculino', 'Masculino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Empresa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
