# Generated by Django 3.0.11 on 2021-11-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211103_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name': 'holerite', 'verbose_name_plural': 'hokerites'},
        ),
        migrations.AddField(
            model_name='usuariocorporativo',
            name='group_permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Group_permissions'),
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='gender',
            field=models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
