# Generated by Django 3.0.11 on 2021-04-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210414_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioendereco',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=7, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Outro', 'Outro'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
