# Generated by Django 3.0.11 on 2021-04-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210416_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioendereco',
            name='tipo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Outro', 'Outro'), ('Feminino', 'Feminino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
