# Generated by Django 3.0.11 on 2021-04-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210413_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='usuariotrabalho',
            name='salariovariavel',
            field=models.DecimalField(blank=True, decimal_places=2, default='00.00', max_digits=6, null=True),
        ),
    ]
