# Generated by Django 3.0.11 on 2021-04-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210416_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Outro', 'Outro'), ('Masculino', 'Masculino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
        migrations.CreateModel(
            name='Contabancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('banco', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Conta')),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UsuarioPessoal')),
            ],
            options={
                'verbose_name': 'Contabancaria',
                'verbose_name_plural': 'Contasbancarias',
            },
        ),
    ]
