# Generated by Django 3.0.11 on 2021-04-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210416_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocorporativo',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Contabancaria'),
        ),
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
