# Generated by Django 3.1.2 on 2021-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210416_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Outro', 'Outro'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
