# Generated by Django 3.2.4 on 2021-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usuariopessoal_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Outro', 'Outro'), ('Feminino', 'Feminino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
