# Generated by Django 3.2.4 on 2021-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_usuariopessoal_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopessoal',
            name='genero',
            field=models.CharField(blank=True, choices=[('Outro', 'Outro'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino')], default='---', max_length=20, null=True, verbose_name='Genero'),
        ),
    ]
