# Generated by Django 3.0.11 on 2021-08-05 16:18

from django.db import migrations, models
import purchases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('requisition_product_id', models.IntegerField(blank=True, null=True, verbose_name='produto da requisição')),
                ('name_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome da imagem')),
                ('image', models.ImageField(blank=True, null=True, upload_to=purchases.models.get_files_path)),
            ],
            options={
                'verbose_name': 'Imagem do produto',
                'verbose_name_plural': 'Imagens dos produtos',
            },
        ),
        migrations.CreateModel(
            name='Purchase_requisition',
            fields=[
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('purchase_requisition_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id da requisição')),
                ('requester', models.CharField(max_length=100, verbose_name='Requisitante')),
                ('manager', models.CharField(max_length=100, verbose_name='Gestor')),
                ('buyer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comprador(a)')),
                ('approved', models.BooleanField(default=False, verbose_name='verificação do gestor ')),
                ('status', models.CharField(default='Aguardando verificação do Gestor', max_length=255, verbose_name='status')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='preço total')),
                ('financial_approval', models.BooleanField(default=False, verbose_name='aprovado pelo financeiro')),
                ('justification', models.CharField(blank=True, max_length=255, null=True, verbose_name='justificativa')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Data de entrega esperado')),
                ('forecast', models.CharField(blank=True, max_length=100, null=True, verbose_name='tempo de  consumo')),
                ('purchase_manager_approval', models.BooleanField(default=False)),
                ('cotation', models.BooleanField(default=False)),
                ('cot', models.DateTimeField(blank=True, null=True)),
                ('boug', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to=purchases.models.get_files_invoice)),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
            },
        ),
        migrations.CreateModel(
            name='Requisition_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('purchase_requisition_id', models.IntegerField(verbose_name='id da requisição')),
                ('requisition_product', models.CharField(max_length=255, verbose_name='Produto')),
                ('price_product', models.CharField(blank=True, max_length=20, null=True, verbose_name='preço do produto')),
                ('first_provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='primeiro fornecedor')),
                ('second_provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo_fornecedor')),
                ('third_provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='terceiro_fornecedor')),
                ('amount', models.IntegerField(default=1, verbose_name='quantidade')),
                ('unit', models.CharField(blank=True, max_length=100, null=True, verbose_name='unidade')),
                ('first_cotation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='primeira cotação')),
                ('second_cotation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='segunda  cotação')),
                ('third_cotation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='trerceira cotação')),
                ('cotations_length', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade de cotações')),
                ('ticket', models.FileField(blank=True, null=True, upload_to=purchases.models.get_files_ticket)),
                ('payment_voucher', models.FileField(blank=True, null=True, upload_to=purchases.models.get_files_voucher)),
                ('type_of_payment', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo de pagamento')),
            ],
            options={
                'verbose_name': 'Produto cotado',
                'verbose_name_plural': 'Produtos cotados',
            },
        ),
    ]
