# Generated by Django 3.0.11 on 2021-08-05 19:01

from django.db import migrations, models
import purchases.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_requisition_product_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_requisition',
            name='invoice',
        ),
        migrations.AddField(
            model_name='requisition_product',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=purchases.models.get_files_invoice),
        ),
    ]
