# Generated by Django 3.0.11 on 2021-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20210805_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition_product',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
