# Generated by Django 3.0.11 on 2021-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_requisition_product_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_requisition',
            name='observation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observação'),
        ),
    ]
