# Generated by Django 3.0.11 on 2021-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_auto_20210807_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_requisition',
            name='return_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo da devolução'),
        ),
    ]
