# Generated by Django 3.0.11 on 2021-08-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_auto_20210817_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_requisition',
            name='return_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo da devolução'),
        ),
    ]
