# Generated by Django 3.0.11 on 2021-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_auto_20210819_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition_product',
            name='delivered_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
