# Generated by Django 3.2.4 on 2021-06-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import performance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('sku', models.IntegerField()),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_active', models.BooleanField(default=False)),
                ('description_complete', models.DateTimeField(blank=True, null=True, verbose_name='description_complete')),
                ('images_active', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('number_images', models.IntegerField(default=0)),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='date_complete')),
                ('edit_by', models.CharField(blank=True, max_length=50, verbose_name='edit_by')),
                ('complete', models.BooleanField(default=False)),
                ('user_image', models.CharField(default='#', max_length=30, verbose_name='user_image')),
                ('image_zero', models.ImageField(blank=True, null=True, upload_to=performance.models.get_files_path)),
                ('image_complete', models.DateTimeField(blank=True, null=True, verbose_name='image_complete')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('meta', models.IntegerField()),
                ('type_meta', models.CharField(choices=[('E.F', 'Editar Foto'), ('E.D', 'Editar Descricao'), ('C.D', 'Criar Descricao'), ('C.F', 'Criar Foto')], max_length=50, verbose_name='type_meta')),
            ],
            options={
                'verbose_name': 'Metas',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=performance.models.get_files_path_profile)),
                ('metas', models.ManyToManyField(to='performance.Metas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('porcentagem', models.IntegerField(default=0)),
                ('conclude', models.IntegerField(default=0)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.metas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('name', models.CharField(default='#', max_length=100, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=performance.models.get_files_path)),
                ('user', models.CharField(max_length=30, verbose_name='user')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.announcement')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Annou_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('changed', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('detail', models.CharField(max_length=255, verbose_name='annou_detail')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.announcement')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
            },
        ),
    ]
