# Generated by Django 3.0.11 on 2021-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('C.D', 'Criar Descricao'), ('E.F', 'Editar Foto'), ('E.D', 'Editar Descricao'), ('C.F', 'Criar Foto')], max_length=50, verbose_name='type_meta'),
        ),
    ]
