# Generated by Django 3.0.11 on 2021-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20210701_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('E.D', 'Editar Descricao'), ('E.F', 'Editar Foto'), ('C.D', 'Criar Descricao'), ('C.F', 'Criar Foto')], max_length=50, verbose_name='type_meta'),
        ),
    ]
