# Generated by Django 3.0.11 on 2021-06-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20210630_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('C.F', 'Criar Foto'), ('C.D', 'Criar Descricao'), ('E.F', 'Editar Foto'), ('E.D', 'Editar Descricao')], max_length=50, verbose_name='type_meta'),
        ),
    ]
