# Generated by Django 3.0.11 on 2021-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20210710_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('C.F', 'Criar Foto'), ('E.F', 'Editar Foto'), ('C.D', 'Criar Descricao'), ('E.D', 'Editar Descricao')], max_length=50, verbose_name='type_meta'),
        ),
    ]
