# Generated by Django 3.0.11 on 2021-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20210713_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('E.D', 'Editar Descricao'), ('C.D', 'Criar Descricao'), ('C.F', 'Criar Foto'), ('E.F', 'Editar Foto')], max_length=50, verbose_name='type_meta'),
        ),
    ]
