# Generated by Django 3.0.11 on 2021-07-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20210714_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('E.D', 'Editar Descricao'), ('C.F', 'Criar Foto'), ('C.D', 'Criar Descricao'), ('E.F', 'Editar Foto')], max_length=50, verbose_name='type_meta'),
        ),
    ]
