# Generated by Django 3.0.11 on 2021-07-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20210714_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('E.F', 'Editar Foto'), ('E.D', 'Editar Descricao'), ('C.F', 'Criar Foto'), ('C.D', 'Criar Descricao')], max_length=50, verbose_name='type_meta'),
        ),
    ]
