# Generated by Django 3.0.11 on 2021-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_auto_20210714_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='type_meta',
            field=models.CharField(choices=[('E.D', 'Editar Descricao'), ('E.F', 'Editar Foto'), ('C.F', 'Criar Foto'), ('C.D', 'Criar Descricao')], max_length=50, verbose_name='type_meta'),
        ),
    ]
