# Generated by Django 3.0.11 on 2021-08-27 12:52

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='codigo')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='categoria')),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço de custo')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário responsavel')),
                ('is_used', models.BooleanField(default=False, verbose_name='em uso')),
                ('quantity_in_use', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade em uso')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('invoice', models.FileField(blank=True, null=True, upload_to=inventory.models.get_files_path, verbose_name='nota fiscal')),
                ('associate', models.CharField(blank=True, max_length=100, null=True, verbose_name='associado')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='local')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='empresa')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'local de armazenagem',
                'verbose_name_plural': 'locais de armazenagem',
            },
        ),
        migrations.CreateModel(
            name='Log_entrance',
            fields=[
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('entrance_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo da entrada')),
                ('creator', models.CharField(max_length=255, verbose_name='criador')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Input')),
            ],
            options={
                'verbose_name': 'Entrada de peça',
                'verbose_name_plural': 'Entrada de peças',
            },
        ),
        migrations.CreateModel(
            name='Log_defect',
            fields=[
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('defect_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo do defeito')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('creator', models.CharField(max_length=255, verbose_name='criador')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Input')),
            ],
            options={
                'verbose_name': 'Defeito',
                'verbose_name_plural': 'Defeitos',
            },
        ),
        migrations.CreateModel(
            name='Log_association',
            fields=[
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('association_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo da Associação')),
                ('associate', models.CharField(blank=True, max_length=100, null=True, verbose_name='associado')),
                ('creator', models.CharField(max_length=255, verbose_name='criador')),
                ('action', models.CharField(max_length=100, verbose_name='Ação')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Input')),
            ],
            options={
                'verbose_name': 'Associação',
                'verbose_name_plural': 'Associações',
            },
        ),
        migrations.AddField(
            model_name='input',
            name='localization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Places'),
        ),
    ]
