# Generated by Django 3.0.11 on 2021-08-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='Inputs',
        ),
    ]
