# Generated by Django 3.0.11 on 2021-08-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210827_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='cep')),
                ('public_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Número')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='Uf')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('complement', models.CharField(blank=True, max_length=10, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereços do fornecedor',
                'verbose_name_plural': 'Endereços dos fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Stock_loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('road', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('side', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lado')),
                ('shelf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pratileira')),
                ('drawer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Graveta')),
            ],
            options={
                'verbose_name': 'Localização do estoque ',
                'verbose_name_plural': 'Localizações do estoque',
            },
        ),
        migrations.AddField(
            model_name='inputs',
            name='available_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade disponivel'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='average_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='custo medio'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='bar_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de barras'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destinação'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data que acabou'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='maximum_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantidade maxima'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='minimum_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantidade minima'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='output_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantidade de saida'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='product_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Produto'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='shipping_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor do frete'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='apelido'),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('manufacturer_code', models.IntegerField(blank=True, null=True, verbose_name='codigo')),
                ('person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='fornecedor')),
                ('fantasy', models.CharField(blank=True, max_length=255, null=True, verbose_name='fantasia')),
                ('industry', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ramo de atividade')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30, null=True, verbose_name='cpf/cnpj')),
                ('ie_rg', models.CharField(blank=True, max_length=30, null=True, verbose_name='IE/RG')),
                ('ie_indicator', models.CharField(blank=True, max_length=50, null=True, verbose_name='indicador IE')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo')),
                ('telephone1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone1')),
                ('telephone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('e_mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('tax_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail fiscal')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Manufacturer_address')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='tel/Cel')),
                ('manufacturer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacturer')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.AddField(
            model_name='inputs',
            name='manufacturer_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Manufacturer'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='stock_loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Stock_loc'),
        ),
    ]
