# Generated by Django 3.0.11 on 2021-07-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_log_cat_entrance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_pro_entrance',
            fields=[
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pro_entrance_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo da entrada')),
                ('category_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Product')),
            ],
            options={
                'verbose_name': 'Entrada de categoria',
                'verbose_name_plural': 'Entrada de categorias',
            },
        ),
    ]
