# Generated by Django 3.2.4 on 2021-06-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='details',
            field=models.CharField(default=12, max_length=255, verbose_name='detalhes da peça'),
            preserve_default=False,
        ),
    ]
