# Generated by Django 3.2.4 on 2021-06-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_details_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_entrance',
            name='amount',
        ),
    ]
