# Generated by Django 3.0.11 on 2021-09-18 11:27

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210831_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='output_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade de saida'),
        ),
        migrations.CreateModel(
            name='Log_Movimantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('modifyer', models.CharField(blank=True, max_length=100, null=True, verbose_name='atuante')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descrição')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='codigo')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='categoria')),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preço de custo')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário responsavel')),
                ('is_used', models.BooleanField(default=False, verbose_name='em uso')),
                ('quantity_in_use', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade em uso')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('invoice', models.FileField(blank=True, null=True, upload_to=inventory.models.get_files_path, verbose_name='nota fiscal')),
                ('associate', models.CharField(blank=True, max_length=100, null=True, verbose_name='associado')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='apelido')),
                ('output_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade de saida')),
                ('maximum_amount', models.IntegerField(blank=True, null=True, verbose_name='quantidade maxima')),
                ('minimum_quantity', models.IntegerField(blank=True, null=True, verbose_name='quantidade minima')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('bar_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de barras')),
                ('available_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantidade disponivel')),
                ('destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Destinação')),
                ('shipping_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='valor do frete')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='custo medio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data que acabou')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Produto')),
                ('localization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Places')),
                ('manufacturer_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Manufacturer')),
                ('stock_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Stock_loc')),
            ],
            options={
                'verbose_name': 'Log_movimentação',
                'verbose_name_plural': 'Log_movimentação',
            },
        ),
    ]
