# Generated by Django 3.0.11 on 2021-07-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_log_pro_entrance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_entrance',
            options={'verbose_name': 'Entrada de peça', 'verbose_name_plural': 'Entrada de peças'},
        ),
        migrations.AlterModelOptions(
            name='log_pro_entrance',
            options={'verbose_name': 'Entrada de produto', 'verbose_name_plural': 'Entrada de produtos'},
        ),
    ]
