# Generated by Django 3.0.11 on 2021-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210918_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputs',
            name='entry_quantitaty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade de entrada'),
        ),
        migrations.AddField(
            model_name='log_movimantation',
            name='entry_quantitaty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='quantidade de entrada'),
        ),
    ]
