# Generated by Django 3.0.11 on 2021-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210918_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer_address',
            name='addresse_code',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='codigo do endereço'),
        ),
    ]
