# Generated by Django 3.0.11 on 2021-09-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_manufacturer_address_addresse_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer_address',
            old_name='addresse_code',
            new_name='address_code',
        ),
    ]
