# Generated by Django 3.0.11 on 2021-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210918_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer_address',
            name='address_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='codigo do endereço'),
        ),
    ]
