# Generated by Django 3.0.11 on 2021-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210920_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='obeservasão'),
        ),
    ]
