# Generated by Django 3.0.11 on 2021-10-05 20:16

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='descrição')),
                ('reserve', models.CharField(blank=True, max_length=10, null=True, verbose_name='User')),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('start', models.CharField(blank=True, max_length=50, null=True, verbose_name='start')),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('data_end', models.CharField(blank=True, max_length=50, null=True, verbose_name='end')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Dashbaners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image', models.FileField(upload_to=files.models.get_banner_path, verbose_name='banner')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='gestor')),
                ('geral', models.BooleanField(default=False)),
                ('timeshow', models.DateField(blank=True, null=True)),
                ('order_by', models.IntegerField(blank=True, null=True, verbose_name='ordem de exibição')),
                ('expired', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'dashbaner',
                'verbose_name_plural': 'dashbaners',
            },
        ),
        migrations.CreateModel(
            name='Report_human_resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('file', models.FileField(blank=True, null=True, upload_to='models_rh/')),
                ('file_name', models.CharField(max_length=100, verbose_name='nome')),
                ('file_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='category')),
            ],
            options={
                'verbose_name': 'Relatorio RH',
                'verbose_name_plural': 'Relatorios RH',
            },
        ),
    ]
