# Generated by Django 3.0.11 on 2021-07-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('file', models.FileField(upload_to='models_rh')),
                ('file_name', models.CharField(max_length=100, verbose_name='nome')),
                ('file_category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('file_datetime', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
