# Generated by Django 3.0.11 on 2021-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização _'),
        ),
    ]
