# Generated by Django 3.0.11 on 2021-07-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_datetime',
        ),
    ]
