# Generated by Django 3.0.11 on 2021-10-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20211005_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='data_end',
            new_name='dt_end',
        ),
    ]
