# Generated by Django 3.0.11 on 2021-07-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_file_file_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Report_human_resources',
        ),
        migrations.AlterModelOptions(
            name='report_human_resources',
            options={'verbose_name': 'Relatorio RH', 'verbose_name_plural': 'Relatorios RH'},
        ),
    ]
