# Generated by Django 3.0.11 on 2021-07-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210723_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_human_resources',
            name='file',
            field=models.FileField(upload_to='models_rh/'),
        ),
    ]
