# Generated by Django 3.0.11 on 2021-07-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210723_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_human_resources',
            name='file',
            field=models.FileField(blank=True, upload_to='models_rh/'),
        ),
    ]
