# Generated by Django 3.0.11 on 2021-09-09 20:22

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20210723_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashbaners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Criacao')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Atualizacao')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image', models.FileField(upload_to=files.models.get_banner_path, verbose_name='banner')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='gestor')),
                ('geral', models.BooleanField(default=False)),
                ('timeshow', models.CharField(default='30', max_length=4, verbose_name='tempo de exibiçao')),
                ('order_by', models.IntegerField(blank=True, null=True, verbose_name='ordem de exibição')),
            ],
            options={
                'verbose_name': 'dashbaner',
                'verbose_name_plural': 'dashbaners',
            },
        ),
    ]
